services:
  - type: web
    name: unispa
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://unispa.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: APP_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
